### ISSUE TITLE
Bold is hard to read for dark variety

### ISSUE THREAD

**Issue by vrinek** [csutter/chester-iterm2-colors#2]
On the dark variety of the colour scheme, "Background" is #28303e (dark grey), "Bold" is #0a0a0a (essentially black) and "Foreground" is #c4cfd4 (light grey). This makes Bold really hard to read.

<img width="720" alt="screen shot 2016-06-29 at 15 31 53" src="https://cloud.githubusercontent.com/assets/81346/16456108/a3543c10-3e0e-11e6-847c-4f2782e1b6f7.png">

Personally, I changed "Bold" to #ecf9ff which looks quite better.

<img width="527" alt="screen shot 2016-06-29 at 15 35 09" src="https://cloud.githubusercontent.com/assets/81346/16456214/15798174-3e0f-11e6-8cd4-06e08d5dbe8d.png">

**Comment by hexacera** [comment]
Having the same problem, especially when reading the man pages

**Comment by hexacera** [comment]
@vrinek Just found out that disabling `Draw bold text in bright colors` under *Profiles - Text - Text Rendering* can do a temporary fix

**Comment by vrinek** [comment]
This is not relevant to me anymore, and it's been 4y since last updated, so I'll close this issue.
